version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${DJANGO_PORT}:8000"
    command: "sh /entrypoint.sh"
    env_file:
      - ../.env.prod
    depends_on:
      - postgres
      - redis
    volumes:
      - ..:/app/

  postgres:
    image: postgres:latest
    container_name: medcenter-db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env.prod
    restart: always

  redis:
    image: redis:alpine
    container_name: medcenter-redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
  static_volume:
