# Generated by Django 5.2 on 2025-06-07 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=25, verbose_name='Отчество')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['last_name', 'first_name', 'patronymic'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('datetime_begin', models.DateTimeField(verbose_name='Дата начала работы расписания')),
                ('datetime_end', models.DateTimeField(verbose_name='Дата окончания')),
                ('monday', models.BooleanField(default=False, verbose_name='Понедельник')),
                ('tuesday', models.BooleanField(default=False, verbose_name='Вторник')),
                ('wednesday', models.BooleanField(default=False, verbose_name='Среда')),
                ('thursday', models.BooleanField(default=False, verbose_name='Четверг')),
                ('friday', models.BooleanField(default=False, verbose_name='Пятница')),
                ('saturday', models.BooleanField(default=False, verbose_name='Суббота')),
                ('sunday', models.BooleanField(default=False, verbose_name='Воскресенье')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['-datetime_begin'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=25, verbose_name='Название специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время создания')),
                ('number', models.IntegerField(verbose_name='Номер талона')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.person', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Талон',
                'verbose_name_plural': 'Талоны',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medcenter.person', verbose_name='Персональные данные')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.specialization', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'ordering': ['person__last_name', 'person__first_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cabinet_number', models.IntegerField(verbose_name='Номер кабинета')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.schedule', verbose_name='Расписание')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Расписание работы',
                'verbose_name_plural': 'Расписания работы',
                'ordering': ['doctor', 'schedule__datetime_begin'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.specialization', verbose_name='Специальность')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.ticket', verbose_name='Талон')),
            ],
            options={
                'verbose_name': 'Приём',
                'verbose_name_plural': 'Приёмы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='doctors',
            field=models.ManyToManyField(through='medcenter.DoctorSchedule', to='medcenter.doctor', verbose_name='Врачи'),
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medcenter.ticket', verbose_name='Талон')),
                ('time_begin', models.DateTimeField(verbose_name='Время начала приема')),
                ('time_end', models.DateTimeField(verbose_name='Время окончания приема')),
                ('doctor_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.doctorschedule', verbose_name='Расписание врача')),
            ],
            options={
                'verbose_name': 'Очередь',
                'verbose_name_plural': 'Очередь',
                'ordering': ['time_begin'],
            },
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('completed', False)), fields=('number',), name='unique_uncompleted_ticket_number'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('ticket', 'specialization'), name='unique_ticket_specialization'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.UniqueConstraint(fields=('doctor', 'schedule', 'cabinet_number'), name='unique_doctor_schedule_cabnumber'),
        ),
    ]
