# Generated by Django 5.2 on 2025-05-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='cabinet_number',
            field=models.IntegerField(verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
    ]
