# Generated by Django 5.2 on 2025-06-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcenter', '0002_alter_doctorschedule_cabinet_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Приём', 'verbose_name_plural': 'Приёмы'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['person__last_name', 'person__first_name'], 'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['doctor', 'schedule__datetime_begin'], 'verbose_name': 'Расписание работы', 'verbose_name_plural': 'Расписания работы'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name', 'patronymic'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-datetime_begin'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['title'], 'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-datetime'], 'verbose_name': 'Талон', 'verbose_name_plural': 'Талоны'},
        ),
        migrations.AlterModelOptions(
            name='waitinglist',
            options={'ordering': ['time_begin'], 'verbose_name': 'Очередь', 'verbose_name_plural': 'Очередь'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.specialization', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.ticket', verbose_name='Талон'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medcenter.person', verbose_name='Персональные данные'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.specialization', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='cabinet_number',
            field=models.IntegerField(verbose_name='Номер кабинета'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.schedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='datetime_begin',
            field=models.DateTimeField(verbose_name='Дата начала работы расписания'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='doctors',
            field=models.ManyToManyField(through='medcenter.DoctorSchedule', to='medcenter.doctor', verbose_name='Врачи'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Название специальности'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(verbose_name='Номер талона'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.person', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='doctor_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcenter.doctorschedule', verbose_name='Расписание врача'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medcenter.ticket', verbose_name='Талон'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='time_begin',
            field=models.DateTimeField(verbose_name='Время начала приема'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='time_end',
            field=models.DateTimeField(verbose_name='Время окончания приема'),
        ),
    ]
