# Generated by Django 5.2 on 2025-06-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcenter', '0003_alter_appointment_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('completed', False)), fields=('number',), name='unique_uncompleted_ticket_number'),
        ),
    ]
