# Generated by Django 5.2 on 2025-06-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_phone_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
